# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 951)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(30, 830, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1113, 816))
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.viewButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewButton.setGeometry(QtCore.QRect(210, 830, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.viewButton.setFont(font)
        self.viewButton.setObjectName("viewButton")
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(390, 830, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(940, 830, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "Add Mole"))
        self.viewButton.setText(_translate("MainWindow", "View Mole"))
        self.removeButton.setText(_translate("MainWindow", "Remove Mole"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
